name: WarPlugin
version: '1.0-SNAPSHOT'
main: de.redjulu.warPlugin.WarPlugin
api-version: '1.20'

author: RedJulu

commands:
  vanish:
    aliases: [v]
  money:
  rank:
    aliases: [rang]
  invsee:
  bank: